import {
  BookOpen,
  Calendar,
  School,
  ShieldCheck,
  CreditCard,
  Mic,
  Plane,
  Mic2,
  LetterText,
  Mail,
  Banknote,
  HandCoins,
  WholeWord,
  MapPinned,
  MessagesSquare,
  FileText,
  ClipboardCheck,
  BadgeCheck,
  PlaneTakeoff,
  FileWarning,
  Wallet,
  BadgeDollarSign,
  FilePenLine,
  Route,
  FolderX,
  Files,
  ClockAlert,
  CalendarClock,
  MapPin,
  Phone,
  MessageCircle,
  ArrowRight,
  FileCheck,
  Landmark,
  FileUser,
  Briefcase,
  Monitor,
  GraduationCap,
  BadgeIndianRupee,
  Building2,
  House,
  UserCheck,
  FilePlusCorner,
  ClipboardClock
} from "lucide-react";

export const icons = {
    "CreditCard":CreditCard,
    "Mail":Mail,
    "Mic2":Mic2,
    "Mic":Mic,
    "Banknote":Banknote,
    "HandCoins":HandCoins,
    "Plane":Plane,
    "MapPinned":MapPinned,
    "MessagesSquare":MessagesSquare,
    "FileText":FileText,
    "ClipboardCheck":ClipboardCheck,
    "BadgeCheck":BadgeCheck,
    "PlaneTakeoff":PlaneTakeoff,
    "FileWarning": FileWarning,
    "Wallet": Wallet,
    "BadgeDollarSign": BadgeDollarSign,
    "FilePenLine": FilePenLine,
    "Route": Route,
    "FolderX": FolderX,
    "Files": Files,
    "ClockAlert": ClockAlert,
    "CalendarClock": CalendarClock,
    "MapPin":MapPin, 
    "Phone":Phone,
    "ArrowRight":ArrowRight,
    "MessageCircle":MessageCircle,
    "ShieldCheck":ShieldCheck,
    "BookOpen":BookOpen,
    "Calendar":Calendar,
    "School":School,
    "LetterText":LetterText,
    "FileUser":FileUser,
    "FileCheck":FileCheck,
    "LandMark":Landmark,
    "Briefcase":Briefcase,
    "Monitor":Monitor,
    "GraduationCap":GraduationCap,
    "BadgeIndianRupee":BadgeIndianRupee,
    "Building2":Building2,
    "House":House,
    "UserCheck":UserCheck,
    "FilePlusCorner":FilePlusCorner,
    "ClipboardClock":ClipboardClock,
    
  }

  