// --- Data ---
export const testimonialsData2 = [
  {
    id: 1,
    tag: "AFTER CANADA REFUSAL",
    tagColor: "bg-red-50 text-red-700 border-red-100",
    description:
      "Vikrant Bawa from Gurdaspur successfully got his USA Study Visa after a previous Canada refusal.",
    name: "Vikrant Bawa",
    visa: "USA Study Visa",
    location: "Gurdaspur, Punjab",
    initials: "VB",
    priority: true,
    videoUrl: "BRK8i5Szdsk",
  },
  {
    id: 2,
    tag: "AFTER 2 REFUSALS",
    tagColor: "bg-red-50 text-red-700 border-red-100",
    description:
      "Rajveer turned his 2 previous refusals into an approval with our expert profile building and pod practice.",
    name: "Rajveer Singh",
    visa: "USA Study Visa",
    location: "India",
    initials: "RS",
    priority: true,
    videoUrl: "dQw4w9WgXcQ",
  },
  {
    id: 3,
    tag: "LOW MARKS & 5.5 IELTS",
    tagColor: "bg-amber-50 text-amber-700 border-amber-100",
    description:
      "Amanpreet from Delhi overcame low 12th marks, a 2-year gap, and a 5.5 IELTS score to get her USA Visa.",
    name: "Amanpreet Kaur",
    visa: "USA Study Visa",
    location: "Delhi, India",
    initials: "AK",
    // Direct video upload example
    videoUrl: "dQw4w9WgXcQ",
  },
  {
    id: 4,
    tag: "2024 BATCH",
    tagColor: "bg-blue-50 text-blue-700 border-blue-100",
    description:
      "A 6-year gap didn't stop him. Our profile strategy helped him secure a visa from a tough consular region.",
    name: "Vikram Singh",
    visa: "USA Study Visa",
    location: "Chandigarh, India",
    initials: "VS",
    videoUrl: "dQw4w9WgXcQ",
  },
  {
    id: 5,
    tag: "FIRST ATTEMPT",
    tagColor: "bg-emerald-50 text-emerald-700 border-emerald-100",
    description:
      "Simran got her visa in the first attempt with just 3 days of preparation.",
    name: "Simran Kaur",
    visa: "USA Study Visa",
    location: "Amritsar, India",
    initials: "SK",
    poster: "/testimonials/simran-poster.jpg",
    videoUrl: "dQw4w9WgXcQ",
  },
  {
    id: 6,
    tag: "COMMUNITY COLLEGE",
    tagColor: "bg-purple-50 text-purple-700 border-purple-100",
    description:
      "Even with a community college I-20, our strategy helped him prove strong ties.",
    name: "Harpreet Singh",
    visa: "USA Study Visa",
    location: "Ludhiana, India",
    initials: "HS",
    poster: "/testimonials/harpreet-poster.jpg",
    videoUrl: "dQw4w9WgXcQ",
  },
  {
    id: 7,
    tag: "MASTER'S DEGREE",
    tagColor: "bg-indigo-50 text-indigo-700 border-indigo-100",
    description:
      "Secured a visa for a Master's in CS at a top 50 university despite a low GRE.",
    name: "Anjali Sharma",
    visa: "USA Study Visa",
    location: "Jaipur, India",
    initials: "AS",
    poster: "/testimonials/anjali-poster.jpg",
    videoUrl: "dQw4w9WgXcQ",
  },
  {
    id: 8,
    tag: "PHD SCHOLAR",
    tagColor: "bg-slate-100 text-slate-700 border-slate-200",
    description:
      "Fully funded PhD offer. We helped him navigate administrative processing smoothly.",
    name: "Rohan Mehta",
    visa: "USA Study Visa",
    location: "Mumbai, India",
    initials: "RM",
    poster: "/testimonials/rohan-poster.jpg",
    videoUrl: "dQw4w9WgXcQ",
  },

  {
    id: 9,
    tag: "FIRST ATTEMPT",
    tagColor: "bg-emerald-50 text-emerald-700 border-emerald-100",
    description:
      "Simran got her visa in the first attempt with just 3 days of preparation.",
    name: "Simran Kaur",
    visa: "USA Study Visa",
    location: "Amritsar, India",
    initials: "SK",
    poster: "/testimonials/simran-poster.jpg",
    videoUrl: "dQw4w9WgXcQ",
  },
  {
    id: 10,
    tag: "COMMUNITY COLLEGE",
    tagColor: "bg-purple-50 text-purple-700 border-purple-100",
    description:
      "Even with a community college I-20, our strategy helped him prove strong ties.",
    name: "Harpreet Singh",
    visa: "USA Study Visa",
    location: "Ludhiana, India",
    initials: "HS",
    poster: "/testimonials/harpreet-poster.jpg",
    videoUrl: "dQw4w9WgXcQ",
  },
  {
    id: 11,
    tag: "MASTER'S DEGREE",
    tagColor: "bg-indigo-50 text-indigo-700 border-indigo-100",
    description:
      "Secured a visa for a Master's in CS at a top 50 university despite a low GRE.",
    name: "Anjali Sharma",
    visa: "USA Study Visa",
    location: "Jaipur, India",
    initials: "AS",
    poster: "/testimonials/anjali-poster.jpg",
    videoUrl: "dQw4w9WgXcQ",
  },
  {
    id: 12,
    tag: "PHD SCHOLAR",
    tagColor: "bg-slate-100 text-slate-700 border-slate-200",
    description:
      "Fully funded PhD offer. We helped him navigate administrative processing smoothly.",
    name: "Rohan Mehta",
    visa: "USA Study Visa",
    location: "Mumbai, India",
    initials: "RM",
    poster: "/testimonials/rohan-poster.jpg",
    videoUrl: "dQw4w9WgXcQ",
  },

  {
    id: 13,
    tag: "LOW MARKS & 5.5 IELTS",
    tagColor: "bg-amber-50 text-amber-700 border-amber-100",
    description:
      "Amanpreet from Delhi overcame low 12th marks, a 2-year gap, and a 5.5 IELTS score to get her USA Visa.",
    name: "Amanpreet Kaur",
    visa: "USA Study Visa",
    location: "Delhi, India",
    initials: "AK",
    poster: "/testimonials/amanpreet-poster.jpg",
    // Direct video upload example
    videoUrl: "/testimonials/amanpreet-video.mp4",
  },
];
